WARD_REGION_MAP = {
    1: "Etobicoke",
    2: "Etobicoke",
    3: "Etobicoke",
    4: "Etobicoke",
    5: "North York",
    6: "North York",
    7: "North York",
    8: "York",
    9: "York",
    10: "York",
    11: "Downtown",
    12: "North York",
    13: "North York",
    14: "Downtown",
    15: "North York",
    16: "North York",
    17: "North York",
    18: "Scarborough",
    19: "Scarborough",
    20: "Scarborough",
    21: "Scarborough",
    22: "Scarborough",
    23: "Scarborough",
    24: "Scarborough",
    25: "Scarborough"
}